# Generated by Django 3.0.2 on 2020-01-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundown_api', '0002_auto_20200130_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user_profile',
            new_name='user',
        ),
    ]
