# Generated by Django 3.0.2 on 2020-01-30 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown_api', '0004_auto_20200130_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
