# Generated by Django 3.0.2 on 2020-01-31 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown_api', '0005_auto_20200130_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundown',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rundowndetail',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='rundowndetail',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='rundowndetail',
            name='with_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
