# Generated by Django 3.0.2 on 2020-01-31 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown_api', '0008_auto_20200131_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
