# Generated by Django 3.0.2 on 2020-02-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rundown_api', '0010_auto_20200131_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='requested_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
